lib/quoteme_web/router.ex
defmodule QuoteMeWeb.Router do
  use QuoteMeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", QuoteMeWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/search", SearchController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", QuoteMeWeb do
  #   pipe_through :api
  # end
end

lib/quoteme_web/controllers/search_controller.ex
defmodule QuoteMeWeb.SearchController do
  use QuoteMeWeb, :controller

  alias QuoteMe.Cinema

  def index(conn, %{"query" => search_query}) do
    search_results = Cinema.search(search_query)
    render(conn, "index.html", search_results: search_results, search_query: search_query)
  end

  # def show(conn, %{"id" => id}) do
  #   search = Cinema.get_search!(id)
  #   render(conn, "show.html", search: search)
  # end

end

lib/quoteme_web/views/search_view.ex
defmodule QuoteMeWeb.SearchView do
  use QuoteMeWeb, :view
  import QuoteMe.SearchUtil, only: [strip_query: 1]
end

lib/quoteme_web/templates/search/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/quoteme_web/templates/search/index.html.eex
<h2>Listing Search Results</h2>
<h5>for '<i><%= strip_query(@search_query) %></i>' </h5>

<table>
  <thead>
    <tr>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for search_result <- @search_results do %>
    <tr>

      <td>
        <span><%= search_result.name %></span>
      </td>
      <td>
        <span>... <%= raw search_result.highlight %> ...</span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Search", to: Routes.page_path(@conn, :index) %></span>

lib/quoteme_web/templates/search/new.html.eex
<h1>New Search</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.search_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.search_path(@conn, :index) %></span>

lib/quoteme_web/templates/search/show.html.eex
<h1>Show Search</h1>

<ul>

</ul>

<span><%= link "Edit", to: Routes.search_path(@conn, :edit, @search) %></span>
<span><%= link "Back", to: Routes.search_path(@conn, :index) %></span>